import Header from "@/components/sections/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main className="max-w-7xl lg:mx-auto pt-10 px-4 xl:px-0">
        {children}
      </main>
    </div>
  );
}
